/**
 * Token build pipeline — single source of truth.
 *
 * Reads the structured JSON token definitions and generates the CSS files:
 *   - src/styles/tokens/core.json     -> src/styles/tokens/core.css
 *   - src/styles/tokens/semantic.json -> src/styles/tokens/semantic.css
 *
 * The generated CSS is byte-for-byte identical to the hand-authored files.
 * Run with:  pnpm tokens   (node scripts/build-tokens.ts)
 *
 * To change a token value: edit the JSON, then re-run `pnpm tokens`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface Token {
  name: string;
  value: string;
  /** Comment line(s) rendered immediately above this token (no blank line separates them). */
  commentBefore?: string;
  /** Insert a blank line before this token (used to visually separate sub-blocks). */
  blankBefore?: boolean;
}

interface Group {
  /** Group header comment (may span multiple lines). */
  comment: string;
  tokens: Token[];
}

interface TokenFile {
  /** Header comment text (without the surrounding slash-star markers). */
  header: string;
  groups: Group[];
}

const HERE = dirname(fileURLToPath(import.meta.url));
const TOKENS_DIR = join(HERE, "..", "src", "styles", "tokens");

/** Indent every line of a comment block by two spaces (the :root body indent). */
function indentComment(comment: string): string {
  return comment
    .split("\n")
    .map((line) => `  ${line}`)
    .join("\n");
}

/** Render a token declaration, indenting continued value lines to 4 spaces. */
function renderToken(token: Token): string {
  const lines: string[] = [];
  if (token.commentBefore) {
    lines.push(indentComment(token.commentBefore));
  }
  const valueLines = token.value.split("\n");
  if (valueLines.length === 1) {
    lines.push(`  ${token.name}: ${token.value};`);
  } else {
    // First value fragment stays on the declaration line; the rest keep their
    // original 4-space indentation as stored in the JSON value. When the value
    // starts on the next line, the first fragment is empty and no space follows
    // the colon.
    const firstLine =
      valueLines[0] === "" ? `  ${token.name}:` : `  ${token.name}: ${valueLines[0]}`;
    lines.push(firstLine);
    for (let i = 1; i < valueLines.length; i++) {
      lines.push(valueLines[i]);
    }
    lines[lines.length - 1] += ";";
  }
  return lines.join("\n");
}

function generate(data: TokenFile): string {
  const out: string[] = [];
  out.push(`/* ${data.header} */`);
  out.push(":root {");
  data.groups.forEach((group, groupIndex) => {
    if (groupIndex > 0) out.push("");
    out.push(indentComment(group.comment));
    for (const token of group.tokens) {
      if (token.blankBefore) out.push("");
      out.push(renderToken(token));
    }
  });
  out.push("}");
  return `${out.join("\n")}\n`;
}

function allNames(data: TokenFile): string[] {
  return data.groups.flatMap((group) => group.tokens.map((token) => token.name));
}

/** Build the TS union-type file from the token names. */
function generateTypes(coreNames: string[], semanticNames: string[]): string {
  const all = [...coreNames, ...semanticNames];
  const colorNames = all.filter((name) => name.startsWith("--color-"));
  const tokenNames = all.filter((name) => name.startsWith("--token-"));

  const union = (names: string[]): string => names.map((name) => `  | "${name}"`).join("\n");

  return `// AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand.
// Run \`pnpm tokens\` after changing the token JSON to regenerate.

/** Raw palette / primitive design tokens (\`--color-*\`). */
export type ColorToken =
${union(colorNames)};

/** Sizing, spacing, radius, shadow and typography tokens (\`--token-*\`). */
export type SizingToken =
${union(tokenNames)};

/** Any design token exposed as a CSS custom property. */
export type DesignToken = ColorToken | SizingToken;
`;
}

function build(): void {
  const targets: Array<{ json: string; css: string }> = [
    { json: "core.json", css: "core.css" },
    { json: "semantic.json", css: "semantic.css" },
  ];
  const parsed: Record<string, TokenFile> = {};
  for (const { json, css } of targets) {
    const jsonPath = join(TOKENS_DIR, json);
    const cssPath = join(TOKENS_DIR, css);
    const data = JSON.parse(readFileSync(jsonPath, "utf8")) as TokenFile;
    parsed[json] = data;
    const generated = generate(data);
    // Self-check: if the CSS already exists and differs, report the drift.
    let existing: string | null = null;
    try {
      existing = readFileSync(cssPath, "utf8");
    } catch {
      existing = null;
    }
    if (existing !== null && existing !== generated) {
      console.log(`[tokens] ${css} updated (regenerated from ${json})`);
    } else if (existing === generated) {
      console.log(`[tokens] ${css} up to date`);
    } else {
      console.log(`[tokens] ${css} created`);
    }
    writeFileSync(cssPath, generated);
  }

  const types = generateTypes(allNames(parsed["core.json"]), allNames(parsed["semantic.json"]));
  writeFileSync(join(TOKENS_DIR, "tokens.ts"), types);
  console.log("[tokens] tokens.ts generated");
}

build();
